In [50]:
import numpy as np
import cmath 

#log(theta)
arr = np.array([[np.random.uniform(0,1) for _ in range(2)] for _ in range(5)]).T
weights = np.array([np.random.uniform(0,1) for _ in range(5)])
weights /= np.sum(weights)

arr = np.log(arr)
arr2 = np.copy(arr) 

print(arr)

'''Previous method'''

expectation_log_theta = 0
for i in range(5): 
    expectation_log_theta += weights[i] * arr[:,i]



print(np.exp(expectation_log_theta))

Σ = 0
for i in range(5):
    Σ += weights[i] * np.outer(arr[:,i] - expectation_log_theta,arr[:,i] - expectation_log_theta)

print(Σ)




'''New method'''

for i in range(5): 
    arr2[:,i] = arr2[:,i] - expectation_log_theta

print(np.exp(arr))
print(np.exp(arr2))





[[-1.2071577  -0.69691541 -0.17642839 -0.58094788 -0.66486784]
 [-0.10142123 -1.34356185 -0.14049235 -1.07717363 -0.930696  ]]
[0.51652253 0.40214742]
[[ 0.05694965 -0.00713241]
 [-0.00713241  0.18657746]]
[[0.29904605 0.49811943 0.8382588  0.5593679  0.5143415 ]
 [0.90355235 0.26091467 0.86893032 0.34055671 0.3942792 ]]
[[0.57896032 0.96437116 1.62288914 1.08294967 0.99577747]
 [2.24681875 0.64880356 2.16072585 0.84684544 0.9804345 ]]


In [2]:
import numpy as np

np.log(2.7)

0.9932517730102834