In [45]:
import numpy as np
import cmath 

#log(theta)
arr = np.array([[np.random.uniform(0,1) for _ in range(2)] for _ in range(5)]).T
weights = np.array([np.random.uniform(0,1) for _ in range(5)])
weights /= np.sum(weights)

arr = np.log(arr)
arr2 = np.copy(arr) 

'''Previous method'''

expectation_log_theta = 0
for i in range(5): 
    expectation_log_theta += weights[i] * arr[:,i]

Σ = 0
for i in range(5):
    Σ += weights[i] * np.outer(arr[:,i] - expectation_log_theta,arr[:,i] - expectation_log_theta)

print(Σ)

'''New method'''

for i in range(5): 
    arr2[:,i] = arr2[:,i] - expectation_log_theta

print(np.exp(arr))
print(np.exp(arr2))





[[1.73586969 0.33592115]
 [0.33592115 1.2344373 ]]
[[0.59201638 0.79393562 0.03888335 0.99429838 0.07075444]
 [0.8687233  0.5949316  0.07778927 0.06929921 0.94929193]]
[[2.63055038 3.52775316 0.1727733  4.4180399  0.31438847]
 [2.25190941 1.54218502 0.20164579 0.17963781 2.46075984]]
